# Generated by Django 3.2.7 on 2021-10-21 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('p_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('season_clicks', models.IntegerField(default=0)),
                ('lifetime_clicks', models.IntegerField(default=0)),
                ('ban_status', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=0)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('pwr_1', models.BooleanField(default=False)),
                ('pwr_2', models.BooleanField(default=False)),
                ('pwr_3', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('publish_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
