# Generated by Django 3.2.7 on 2021-10-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_id',
            new_name='id',
        ),
    ]
