# Generated by Django 3.2.7 on 2021-11-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0005_auto_20211024_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pwr_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pwr_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pwr_3',
            field=models.IntegerField(default=0),
        ),
    ]
