# Generated by Django 3.2.7 on 2021-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0006_auto_20211109_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.AddField(
            model_name='profile',
            name='click_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='mouse_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='upgrade_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='upgrade_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='upgrade_3',
            field=models.BooleanField(default=False),
        ),
    ]
